---
title: "Analysis of Fatal Police Shootings in the United States (2015-2022)"
output: html_document
date: "2023-10-05"
---

# Preliminary work
### Installing Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("knitr")

```
### Installing .csv file into R
```{r}
getwd()
all_police_shootings <- read.csv("data/fatal-police-shootings-data.csv")
```
# Basic Data Analysis
### Summary Statistics
```{r}
head(all_police_shootings)
summary(all_police_shootings)
```
# Data Exploration
### Count Number of Subjects
```{r}
dim(all_police_shootings)
```
### Structure and Missing Data
```{r}
str(all_police_shootings)
sapply(all_police_shootings, class)
colSums(is.na(all_police_shootings))
```
# Frequency Tables
```{r}
manner_of_death_freq_table <- table(all_police_shootings$manner_of_death)
armed_freq_table <- table(all_police_shootings$armed)
age_freq_table <- table(all_police_shootings$age)
gender_freq_table <- table(all_police_shootings$gender)
race_freq_table <- table(all_police_shootings$race)
gender_freq_table <- table(all_police_shootings$gender)
state_freq_table <- table(all_police_shootings$state)
mental_illness_freq_table <- table(all_police_shootings$signs_of_mental_illness)
flee_freq_table <- table(all_police_shootings$flee)
body_camera_freq_table <- table(all_police_shootings$body_camera)

print(manner_of_death_freq_table)
print(armed_freq_table)
print(age_freq_table)
print(gender_freq_table)
print(race_freq_table)
print(state_freq_table)
print(mental_illness_freq_table)
print(flee_freq_table)
print(body_camera_freq_table)
```

# Visualizing Clean Data
## Visualization of Raw Data
```{r message = FALSE, error = FALSE, warning= FALSE}
head(all_police_shootings)
library(ggplot2)
ggplot(data = all_police_shootings, aes(x = age)) + geom_histogram(bins = 20, fill = 'grey', color = 'black') + ggtitle ("Age distribution of people involved in incidents")

ggplot(data = all_police_shootings, aes(x = gender)) + geom_bar() + 
  xlab("Gender") + ylab("Count") + ggtitle("Police Shooting by Gender")

ggplot(data = all_police_shootings, aes(x = gender, y = age)) + geom_boxplot() + 
  xlab("Gender") + ylab("Age") + ggtitle("Age Distribution by Gender")

all_police_shootings %>% ggplot(aes(x = race)) + geom_bar() + 
    labs(title = "Composition of Races in Police Shootings") +
    xlab("Race")

ggplot(data = all_police_shootings, mapping = aes(x = gender)) + geom_bar()
```

## Data Cleaning and Manipulation
## Data Visualization

# Possible Research Questions
